version: '3.9'

services:
  api_service:
    image: orders_service:latest
    container_name: "orders_service"
    restart: always
    ports:
      - 8082:8082
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/ordersDB
    depends_on:
      - postgres
    volumes:
      - .m2:/root/.m2
    networks:
      - springApiPostgres-net

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ordersDB
    networks:
      - springApiPostgres-net
networks:
  springApiPostgres-net:
    driver: bridge