version: "3.7"
services:
  registry-service:
    image: vikramsvk1/discovery:08.07
    restart: always
    ports:
      - "8761:8761"
    networks:
      - docker-bridge-network

  gateway-service:
    image: vikramsvk1/gateway:13.7
    restart: always
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka
    networks:
      - docker-bridge-network

  #-------------------CUSTOMERS-SERVICE----------------

  customers-service:
    image: vikramsvk1/customers:13.7
    restart: always
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/customersDB?useSSL=false&allowPublicKeyRetrieval=true
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka
    depends_on:
      - mysqldb
    networks:
      - docker-bridge-network

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - docker-bridge-network
    environment:
      MYSQL_DATABASE: customersDB
      MYSQL_ROOT_PASSWORD: password
    volumes:
      #local dir/files: docker dir/files
      - /home/apps/mysqlDB:/var/lib/mysql

  #-------------------CUSTOMERS-SERVICE ENDS------

  #-------------ORDER_SERVICE---------------------

  orders-service:
    image: vikramsvk1/orders:13.7
    restart: always
    ports:
      - 8083:8083
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/ordersDB
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka
    depends_on:
      - postgres
    networks:
      - docker-bridge-network

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /home/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ordersDB
    networks:
      - docker-bridge-network

  #-------------ORDER_SERVICE END---

  #--------PRODUCTS-----------------

  products-service:
    image: vikramsvk1/products:13.7
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      - eureka.client.service-url.defaultZone=http://registry-service:8761/eureka
    networks:
      - docker-bridge-network

  mongodb:
    image: mongo:latest
#   use   image: mongo:4.4.18     ->WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not  VBox issue
    ports:
      - "27017:27017"
    volumes:
      #local dir/files: docker dir/files
      - /home/apps/mongoData:/data/db
    networks:
      - docker-bridge-network

#-----------PRODUCTS_END------------------

networks:
  docker-bridge-network:
    driver: bridge

