# Use an official Maven image as the base image
FROM maven:3.8.5-openjdk-17 AS build
# Set the working directory in the container
WORKDIR /app
# Copy the pom.xml and the project files to the container
COPY pom.xml .
COPY src ./src
# Build the application using Maven
RUN mvn clean package -DskipTests
FROM eclipse-temurin:17-jdk-focal
# Set the working directory in the container
WORKDIR /app
LABEL authors="Vikram"
COPY --from=build /app/target/*.jar customers_service.jar
ENTRYPOINT ["java","-jar","/customers_service.jar"]