# Build stage
FROM maven:3.8.5-openjdk-17 AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean test package

# Package stage
FROM eclipse-temurin:17-jdk-focal
COPY --from=build /home/app/target/*.jar customers_service.jar
ENTRYPOINT ["java","-jar","/customers_service.jar"]