version: "3.7"
services:
  api_service:
    image: customers_service:latest
    container_name: "customers_service"
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/customersDB?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: customersDB
      MYSQL_ROOT_PASSWORD: password
    volumes:
      #local dir/files: docker dir/files
      - ~/apps/mysqlDB:/var/lib/mysql
networks:
  springapimysql-net:
    driver: bridge