version: "3"
services:
  springBoot_productsService:
    image: products_service:latest
    container_name: "products_service"
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - mongodb_net

  mongodb:
    image: mongo:latest
    container_name: "mongoDBImage1"
    ports:
      - "27017:27017"
    volumes:
      #local dir/files: docker dir/files
      - ~/apps/mongoData:/data/db
    networks:
      - mongodb_net
networks:
  mongodb_net:
    driver: bridge