version: "3"
services:
  products_service:
    image: products:13.7
    container_name: "products_service"
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - mongodb_net

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      #local dir/files: docker dir/files
      - ~/apps/mongoData:/data/db
    networks:
      - mongodb_net
networks:
  mongodb_net:
    driver: bridge