server:
  port: 8088

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/customers/**
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/orders/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost