spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/customers/**
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/orders/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/